# Generated by Django 3.1.1 on 2020-12-18 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('DoB', models.DateField(null=True)),
                ('photo', models.URLField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=100)),
                ('rating', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('year', models.CharField(max_length=5)),
                ('rated', models.CharField(max_length=10)),
                ('datepublish', models.CharField(max_length=100)),
                ('runtime', models.CharField(max_length=25)),
                ('writer', models.CharField(max_length=1000)),
                ('synopsis', models.CharField(max_length=1000)),
                ('country', models.CharField(max_length=100)),
                ('poster', models.URLField()),
                ('imdbID', models.CharField(max_length=30)),
                ('type', models.CharField(max_length=10)),
                ('cast', models.ManyToManyField(to='MovieOn.Cast')),
                ('director', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='MovieOn.director')),
                ('genre', models.ManyToManyField(to='MovieOn.Genre')),
                ('ratings', models.ManyToManyField(to='MovieOn.Rating')),
            ],
        ),
    ]
