# Generated by Django 3.1.1 on 2020-10-21 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fName', models.CharField(max_length=100)),
                ('lName', models.CharField(max_length=100)),
                ('dob', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('datepublish', models.DateField()),
                ('synopsis', models.TextField(blank=True, null=True, verbose_name='Synopsis')),
                ('review', models.TextField(blank=True, null=True, verbose_name='Review')),
                ('rating', models.DecimalField(decimal_places=1, max_digits=3)),
                ('director', models.ManyToManyField(to='MovieOn.Director')),
                ('genre', models.ManyToManyField(to='MovieOn.Genre')),
            ],
        ),
    ]
