# Generated by Django 3.1.1 on 2020-12-18 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MovieOn', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='totalseasons',
            field=models.CharField(max_length=4, null=True),
        ),
    ]
