# Generated by Django 3.1.1 on 2020-12-31 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MovieOn', '0002_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='IMDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imdb_id', models.CharField(max_length=100)),
                ('movie', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='MovieOn.movie')),
            ],
        ),
    ]
