# Generated by Django 3.1.1 on 2020-10-21 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MovieOn', '0002_auto_20201021_1443'),
    ]

    operations = [
        migrations.RenameField(
            model_name='director',
            old_name='dob',
            new_name='DoB',
        ),
        migrations.RenameField(
            model_name='director',
            old_name='fName',
            new_name='First_Name',
        ),
        migrations.RenameField(
            model_name='director',
            old_name='lName',
            new_name='Last_Name',
        ),
    ]
